---
sidebar: sidebar 
permalink: reference-configs-azure.html 
keywords: vm, explore, standard, premium, byol, capacity, maximum, virtual machine, Cloud Volumes ONTAP, supported, configurations, disks, sizes 
summary: Cloud Volumes ONTAP è disponibile in Azure nelle configurazioni PAYGO e BYOL. PER PAYGO, puoi scegliere tra Explore, Standard o Premium. 
---
= Configurazioni supportate in Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP è disponibile in Azure in due opzioni di prezzo: Pay-as-you-go e Bring Your Own License (BYOL). Per il pay-as-you-go, puoi scegliere tra tre configurazioni: Explore, Standard o Premium.



== Configurazioni supportate per licenza

Cloud Volumes ONTAP è disponibile in Azure come sistema a nodo singolo e come coppia di nodi ad alta disponibilità (ha) per la fault tolerance e le operazioni senza interruzioni.

L'aggiornamento di un sistema a nodo singolo a una coppia ha non è supportato. Se si desidera passare da un sistema a nodo singolo a una coppia ha, è necessario implementare un nuovo sistema e replicare i dati dal sistema esistente al nuovo sistema.



=== Sistemi a nodo singolo

Quando si implementa Cloud Volumes ONTAP come sistema a nodo singolo in Azure, è possibile scegliere tra le seguenti configurazioni:

[cols="h,d,d,d,d"]
|===
|  | Esplora | Standard | Premium | BYOL 


| Tipi di macchine virtuali supportati | DS3_v2  a| 
* DS4_v2
* DS13_v2

 a| 
* DS5_v2
* DS14_v2
* DS15_v2

 a| 
* DS3_v2
* DS4_v2
* DS5_v2
* DS13_v2
* DS14_v2
* DS15_v2




| Tipi di disco supportati ^1^ 4+| Dischi gestiti HDD standard, dischi gestiti SSD standard e dischi gestiti SSD Premium 


| Tiering cold dei dati su storage blob | Non supportato 3+| Supportato 


| Capacità massima del sistema (dischi + storage a oggetti) | 2 TIB | 10 TIB | 368 TIB | 368 TIB per licenza 
|===
Note:

. Le migliori prestazioni di scrittura sono abilitate quando si utilizzano gli SSD, ma non quando si utilizza il tipo di macchina virtuale DS3_v2.
. Per il supporto dell'area Azure, vedere https://bluexp.netapp.com/cloud-volumes-global-regions["Cloud Volumes Global Regions"^].




=== Coppie HA

Quando si implementa Cloud Volumes ONTAP come coppia ha in Azure, è possibile scegliere tra le seguenti configurazioni:

[cols="h,d,d,d,d"]
|===
|  | Esplora | Standard | Premium | BYOL 


| Tipi di macchine virtuali supportati | Non supportato  a| 
* DS4_v2
* DS13_v2

 a| 
* DS5_v2
* DS14_v2
* DS15_v2

 a| 
* DS4_v2
* DS5_v2
* DS13_v2
* DS14_v2
* DS15_v2




| Tipi di dischi supportati | Non supportato 3+| Blob di pagina Premium 


| Tiering dei dati cold per lo storage blob ^2^ | Non supportato 3+| Supportato 


| Capacità massima del sistema (dischi + storage a oggetti) | Non supportato | 10 TIB | 368 TIB | 368 TIB per licenza 
|===
Note:

. Per il supporto dell'area Azure, vedere https://bluexp.netapp.com/cloud-volumes-global-regions["Cloud Volumes Global Regions"^].




== Dimensioni dei dischi supportate

In Azure, un aggregato può contenere fino a 12 dischi dello stesso tipo e dimensione.



=== Sistemi a nodo singolo

I sistemi a nodo singolo utilizzano dischi gestiti Azure. Sono supportate le seguenti dimensioni dei dischi:

[cols="3*"]
|===
| SSD Premium | SSD standard | HDD standard 


 a| 
* 500 GiB
* 1 TIB
* 2 TIB
* 4 TIB
* 8 TIB
* 16 TIB
* 32 TIB

 a| 
* 100 GiB
* 500 GiB
* 1 TIB
* 2 TIB
* 4 TIB
* 8 TIB
* 16 TIB
* 32 TIB

 a| 
* 100 GiB
* 500 GiB
* 1 TIB
* 2 TIB
* 4 TIB
* 8 TIB
* 16 TIB
* 32 TIB


|===


=== Coppie HA

Le coppie HA utilizzano i blob di pagina Premium. Sono supportate le seguenti dimensioni dei dischi:

* 500 GiB
* 1 TIB
* 2 TIB
* 4 TIB
* 8 TIB

