---
sidebar: sidebar 
permalink: reference-limits-azure.html 
keywords: limits, maximum, storage, aggregates, disks, volumes, capacity, luns, size, storage virtual machine, SVM, page blobs, ebs, managed disks 
summary: Cloud Volumes ONTAP ha limiti di configurazione dello storage in Azure per fornire operazioni affidabili. Per ottenere prestazioni ottimali, non configurare il sistema ai valori massimi. 
---
= Limiti di storage in Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP ha limiti di configurazione dello storage per garantire operazioni affidabili. Per ottenere prestazioni ottimali, non configurare il sistema ai valori massimi.



== Capacità massima del sistema per licenza

La capacità massima del sistema per un sistema Cloud Volumes ONTAP è determinata dalla relativa licenza. La capacità massima del sistema include lo storage basato su disco e lo storage a oggetti utilizzato per il tiering dei dati. NetApp non supporta il superamento di questo limite.

[cols="25,75"]
|===
| Licenza | Capacità massima del sistema (dischi + storage a oggetti) 


| Esplora | 2 TIB (il tiering dei dati non è supportato con Explore) 


| Standard | 10 TIB 


| Premium | 368 TIB 


| BYOL | 368 TIB per licenza 
|===
.Per ha, il limite di capacità della licenza è per nodo o per l'intera coppia ha?
Il limite di capacità è per l'intera coppia ha. Non è per nodo. Ad esempio, se si utilizza la licenza Premium, è possibile avere fino a 368 TIB di capacità tra entrambi i nodi.



== Limiti di dischi e tiering in base alle dimensioni delle macchine virtuali

I limiti dei dischi riportati di seguito sono specifici per i dischi che contengono dati utente. I limiti non includono il disco di boot e il disco root. Le tabelle riportate di seguito mostrano la capacità massima del sistema in base alle dimensioni delle macchine virtuali con dischi o da soli e con il tiering dei dischi e dei dati cold sullo storage a oggetti.

I limiti dei dischi sono indicati in base alle dimensioni delle macchine virtuali per le licenze Premium e BYOL solo perché non è possibile raggiungere i limiti dei dischi con le licenze Explore o Standard a causa dei limiti di capacità del sistema.

* I sistemi a nodo singolo possono utilizzare dischi gestiti HDD standard, dischi gestiti SSD standard e dischi gestiti SSD Premium, con un massimo di 32 TIB per disco. Il numero di dischi supportati varia in base alle dimensioni della macchina virtuale.
* I sistemi HA utilizzano i blob di pagina Premium come dischi, con un massimo di 8 TIB per blob di pagina. Il numero di dischi supportati varia in base alle dimensioni della macchina virtuale.




=== Nodo singolo con licenza Premium

[cols="14,20,31,33"]
|===
| Dimensione della macchina virtuale | Numero massimo di dischi per nodo | Capacità massima del sistema con i soli dischi | Capacità massima del sistema con dischi e tiering dei dati 


| DS5_v2 | 63 | 368 TIB | 368 TIB 


| DS14_v2 | 63 | 368 TIB | 368 TIB 


| DS15_v2 | 63 | 368 TIB | 368 TIB 
|===


=== Nodo singolo con una o più licenze BYOL


NOTE: Per alcuni tipi di macchine virtuali, sono necessarie diverse licenze BYOL per raggiungere la capacità massima di sistema indicata di seguito. Ad esempio, sono necessarie 6 licenze BYOL per raggiungere 2 PIB con DS5_v2.

[cols="10,18,18,18,18,18"]
|===
| Dimensione della macchina virtuale | Numero massimo di dischi per nodo 2+| Capacità massima del sistema con una licenza 2+| Capacità massima del sistema con più licenze 


2+|  | *Dischi da soli* | *Dischi + tiering dei dati* | *Dischi da soli* | *Dischi + tiering dei dati* 


| DS3_v2 | 15 | 368 TIB | 368 TIB | 480 TIB | 368 TIB x ogni licenza 


| DS4_v2 | 31 | 368 TIB | 368 TIB | 896 TIB | 368 TIB x ogni licenza 


| DS5_v2 | 63 | 368 TIB | 368 TIB | 896 TIB | 368 TIB x ogni licenza 


| DS13_v2 | 31 | 368 TIB | 368 TIB | 896 TIB | 368 TIB x ogni licenza 


| DS14_v2 | 63 | 368 TIB | 368 TIB | 896 TIB | 368 TIB x ogni licenza 


| DS15_v2 | 63 | 368 TIB | 368 TIB | 896 TIB | 368 TIB x ogni licenza 
|===


=== HA si accoppia con una licenza Premium

[cols="14,20,31,33"]
|===
| Dimensione della macchina virtuale | Dischi MAX Data per una coppia ha | Capacità massima del sistema con i soli dischi | Capacità massima del sistema con dischi e tiering dei dati 


| DS5_v2 | 63 | 368 TIB | 368 TIB 


| DS14_v2 | 63 | 368 TIB | 368 TIB 


| DS15_v2 | 63 | 368 TIB | 368 TIB 
|===


=== COPPIE HA con una o più licenze BYOL

[cols="10,18,18,18,18,18"]
|===
| Dimensione della macchina virtuale | Dischi MAX Data per una coppia ha 2+| Capacità massima del sistema con una licenza 2+| Capacità massima del sistema con più licenze 


2+|  | *Dischi da soli* | *Dischi + tiering dei dati* | *Dischi da soli* | *Dischi + tiering dei dati* 


| DS4_v2 | 31 | 368 TIB | 368 TIB | 248 TIB | 368 TIB x ogni licenza 


| DS5_v2 | 63 | 368 TIB | 368 TIB | 504 TIB | 368 TIB x ogni licenza 


| DS13_v2 | 31 | 368 TIB | 368 TIB | 248 TIB | 368 TIB x ogni licenza 


| DS14_v2 | 63 | 368 TIB | 368 TIB | 504 TIB | 368 TIB x ogni licenza 


| DS15_v2 | 63 | 368 TIB | 368 TIB | 504 TIB | 368 TIB x ogni licenza 
|===


== Limiti aggregati

Cloud Volumes ONTAP utilizza lo storage Azure come dischi e li raggruppa in _aggregati_. Gli aggregati forniscono storage ai volumi.

[cols="2*"]
|===
| Parametro | Limite 


| Numero massimo di aggregati | Uguale al limite di dischi 


| Dimensione massima dell'aggregato | 352 TIB di capacità raw per nodo singolo ^1,^ ^2^ 96 TIB di capacità raw per coppie ha ^1^ 


| Dischi per aggregato | 1-12 ^3^ 


| Numero massimo di gruppi RAID per aggregato | 1 
|===
Note:

. Il limite di capacità aggregata si basa sui dischi che compongono l'aggregato. Il limite non include lo storage a oggetti utilizzato per il tiering dei dati.
. Il limite di 352 TIB è supportato a partire da 9.6 P3. Le release precedenti alla 9.6 P3 supportano fino a 200 TIB di capacità raw in un aggregato su un sistema a nodo singolo.
. Tutti i dischi di un aggregato devono avere le stesse dimensioni.




== Limiti di storage logico

[cols="22,22,56"]
|===
| Storage logico | Parametro | Limite 


| *Storage Virtual Machine (SVM)* | Numero massimo di Cloud Volumes ONTAP (coppia ha o nodo singolo) | Un SVM per il servizio dati e un SVM di destinazione utilizzati per il disaster recovery. È possibile attivare la SVM di destinazione per l'accesso ai dati in caso di interruzione della SVM di origine. ^1^ una SVM che serve dati copre l'intero sistema Cloud Volumes ONTAP (coppia ha o nodo singolo). 


.2+| *File* | Dimensione massima | 16 TIB 


| Massimo per volume | In base alle dimensioni del volume, fino a 2 miliardi 


| *Volumi FlexClone* | Profondità del clone gerarchico ^2^ | 499 


.3+| *Volumi FlexVol* | Massimo per nodo | 500 


| Dimensione minima | 20 MB 


| Dimensione massima | 100 TIB 


| *Qtree* | Massimo per volume FlexVol | 4,995 


| *Copie Snapshot* | Massimo per volume FlexVol | 1,023 
|===
Note:

. Cloud Manager non fornisce alcun supporto di configurazione o orchestrazione per il disaster recovery SVM. Inoltre, non supporta attività correlate allo storage su una SVM aggiuntiva. Per il disaster recovery di SVM, è necessario utilizzare System Manager o CLI.
+
** https://library.netapp.com/ecm/ecm_get_file/ECMLP2839856["Guida rapida alla preparazione del disaster recovery per SVM"^]
** https://library.netapp.com/ecm/ecm_get_file/ECMLP2839857["Guida di SVM Disaster Recovery Express"^]


. La profondità dei cloni gerarchici è la profondità massima di una gerarchia nidificata di volumi FlexClone che è possibile creare da un singolo volume FlexVol.




== Limiti dello storage iSCSI

[cols="3*"]
|===
| Storage iSCSI | Parametro | Limite 


.4+| *LUN* | Massimo per nodo | 1,024 


| Numero massimo di mappe LUN | 1,024 


| Dimensione massima | 16 TIB 


| Massimo per volume | 512 


| *igroups* | Massimo per nodo | 256 


.2+| *Iniziatori* | Massimo per nodo | 512 


| Massimo per igroup | 128 


| *Sessioni iSCSI* | Massimo per nodo | 1,024 


.2+| *LIF* | Massimo per porta | 32 


| Massimo per portset | 32 


| *Portset* | Massimo per nodo | 256 
|===